## TASK 9 March
Data Reading Tasks:

In [18]:
## Read the dataset from a CSV file into a pandas DataFrame
import seaborn as sb
import pandas as pd
# Read the CSV file into a pandas DataFrame
sales_df = pd.read_csv(r'C:\Users\123\OneDrive\Documents\Python Tasks\pandas files\sales.csv')
print(sales_df)
cus_df = pd.read_csv(r'C:\Users\123\OneDrive\Documents\Python Tasks\pandas files\customers.csv')
print(cus_df)

     order_id        date region   product     category customer_type  \
0           1  2024-04-12   East    Laptop  Electronics     Returning
1           2  2024-12-14  South   Monitor  Accessories     Returning
2           3  2024-09-27  North     Phone  Accessories           New
3           4  2024-04-16   West     Mouse  Electronics     Returning
4           5  2024-03-12   West     Phone  Electronics     Returning
..        ...         ...    ...       ...          ...           ...
495       496  2024-11-20  South     Mouse  Accessories     Returning
496       497  2024-01-04  North     Phone  Accessories     Returning
497       498  2024-01-16  South  Keyboard  Electronics     Returning
498       499  2024-10-06  North     Phone  Accessories     Returning
499       500  2024-12-01  North   Monitor  Electronics           New

     quantity  price  discount    sales
0           8    590      0.09  4295.20
1           2    262      0.18   429.68
2           5    512      0.09  2329.60
3           1    485      0.09   441.35
4           7    332      0.22  1812.72
..        ...    ...       ...      ...
495         6    314      0.23  1450.68
496         9    369      0.23  2557.17
497         6    722      0.14  3725.52
498         2   1449      0.12  2550.24
499         2    869      0.09  1581.58

[500 rows x 10 columns]
     order_id  customer_rating
0           1                1
1           2                1
2           3                2
3           4                1
4           5                4
..        ...              ...
495       496                3
496       497                4
497       498                4
498       499                1
499       500                1

[500 rows x 2 columns]

In [19]:
## Display the first 8 rows and check the basic structure of the dataset using .info()

print(df.head(8))

NameError: name 'df' is not defined

In [ ]:
## Get statistical summary of numerical columns using .describe()

print(df.describe(include = 'all'))

          OrderID  customer_rating
count  500.000000       500.000000
mean   250.500000         2.480000
std    144.481833         1.118975
min      1.000000         1.000000
25%    125.750000         1.000000
50%    250.500000         2.500000
75%    375.250000         3.000000
max    500.000000         4.000000

In [ ]:
## Check column names and rename any columns for better readability (e.g., rename 'order_id' to 'OrderID')

df.rename(columns={
    'order_id': 'OrderID',
}, inplace=True)
df

     OrderID  customer_rating
0          1                1
1          2                1
2          3                2
3          4                1
4          5                4
..       ...              ...
495      496                3
496      497                4
497      498                4
498      499                1
499      500                1

[500 rows x 2 columns]

##Data Cleaning Tasks:

In [ ]:
## Check for missing values in each column and handle them appropriately

df.isnull().sum()

OrderID            0
customer_rating    0
dtype: int64

In [ ]:
sales_df.fillna({'price': sales_df['price'].median(), 'quantity': sales_df['quantity'].median(),
            'discount': 0, 'sales': sales_df['sales'].median(), 'region': 'Unknown',
              'product': 'Unknown', 'category': 'Unknown', 'customer_type': 'Unknown'}, inplace=True)
sales_df

,order_id,date,region,product,category,customer_type,quantity,price,discount,sales
0,1,2024-04-12,East,Laptop,Electronics,Returning,8,590,0.09,4295.20
1,2,2024-12-14,South,Monitor,Accessories,Returning,2,262,0.18,429.68
2,3,2024-09-27,North,Phone,Accessories,New,5,512,0.09,2329.60
3,4,2024-04-16,West,Mouse,Electronics,Returning,1,485,0.09,441.35
4,5,2024-03-12,West,Phone,Electronics,Returning,7,332,0.22,1812.72
...,...,...,...,...,...,...,...,...,...,...
495,496,2024-11-20,South,Mouse,Accessories,Returning,6,314,0.23,1450.68
496,497,2024-01-04,North,Phone,Accessories,Returning,9,369,0.23,2557.17
497,498,2024-01-16,South,Keyboard,Electronics,Returning,6,722,0.14,3725.52
498,499,2024-10-06,North,Phone,Accessories,Returning,2,1449,0.12,2550.24
499,500,2024-12-01,North,Monitor,Electronics,New,2,869,0.09,1581.58

In [22]:
sales_df.isnull().sum()

order_id         0
date             0
region           0
product          0
category         0
customer_type    0
quantity         0
price            0
discount         0
sales            0
dtype: int64

In [23]:
## Check for duplicate rows and remove any duplicates if found

sales_df.duplicated().sum()

np.int64(0)

In [24]:
sales_df.drop_duplicates(inplace=True)
sales_df

,order_id,date,region,product,category,customer_type,quantity,price,discount,sales
0,1,2024-04-12,East,Laptop,Electronics,Returning,8,590,0.09,4295.20
1,2,2024-12-14,South,Monitor,Accessories,Returning,2,262,0.18,429.68
2,3,2024-09-27,North,Phone,Accessories,New,5,512,0.09,2329.60
3,4,2024-04-16,West,Mouse,Electronics,Returning,1,485,0.09,441.35
4,5,2024-03-12,West,Phone,Electronics,Returning,7,332,0.22,1812.72
...,...,...,...,...,...,...,...,...,...,...
495,496,2024-11-20,South,Mouse,Accessories,Returning,6,314,0.23,1450.68
496,497,2024-01-04,North,Phone,Accessories,Returning,9,369,0.23,2557.17
497,498,2024-01-16,South,Keyboard,Electronics,Returning,6,722,0.14,3725.52
498,499,2024-10-06,North,Phone,Accessories,Returning,2,1449,0.12,2550.24
499,500,2024-12-01,North,Monitor,Electronics,New,2,869,0.09,1581.58

In [29]:
##Convert 'date' column to datetime format
sales_df.rename(columns={'date':'Datetime'}, inplace=True)
sales_df

,order_id,Datetime,region,product,category,customer_type,quantity,price,discount,sales
0,1,2024-04-12,East,Laptop,Electronics,Returning,8,590,0.09,4295.20
1,2,2024-12-14,South,Monitor,Accessories,Returning,2,262,0.18,429.68
2,3,2024-09-27,North,Phone,Accessories,New,5,512,0.09,2329.60
3,4,2024-04-16,West,Mouse,Electronics,Returning,1,485,0.09,441.35
4,5,2024-03-12,West,Phone,Electronics,Returning,7,332,0.22,1812.72
...,...,...,...,...,...,...,...,...,...,...
495,496,2024-11-20,South,Mouse,Accessories,Returning,6,314,0.23,1450.68
496,497,2024-01-04,North,Phone,Accessories,Returning,9,369,0.23,2557.17
497,498,2024-01-16,South,Keyboard,Electronics,Returning,6,722,0.14,3725.52
498,499,2024-10-06,North,Phone,Accessories,Returning,2,1449,0.12,2550.24
499,500,2024-12-01,North,Monitor,Electronics,New,2,869,0.09,1581.58

In [ ]:
cus_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         500 non-null    int64
 1   customer_rating  500 non-null    int64
dtypes: int64(2)
memory usage: 7.9 KB

In [ ]:
cus_df.describe(include='all')

         order_id  customer_rating
count  500.000000       500.000000
mean   250.500000         2.480000
std    144.481833         1.118975
min      1.000000         1.000000
25%    125.750000         1.000000
50%    250.500000         2.500000
75%    375.250000         3.000000
max    500.000000         4.000000

In [ ]:
df_merged = pd.merge(sales_df, cus_df, on='order_id', how='inner')
df_merged.head(2)

,order_id,date,region,product,category,customer_type,quantity,price,discount,sales,customer_rating
0,1,2024-04-12,East,Laptop,Electronics,Returning,8,590,0.09,4295.20,1
1,2,2024-12-14,South,Monitor,Accessories,Returning,2,262,0.18,429.68,1

In [ ]:
df_merged.columns

Index(['order_id', 'date', 'region', 'product', 'category', 'customer_type',
       'quantity', 'price', 'discount', 'sales', 'customer_rating'],
      dtype='object')

In [ ]:
df_merged.drop(columns=['discount'], inplace=True)

In [ ]:
df_merged.columns

Index(['order_id', 'date', 'region', 'product', 'category', 'customer_type',
       'quantity', 'price', 'sales', 'customer_rating'],
      dtype='object')

In [ ]:
df_merged.region.value_counts()

region
North    151
East     118
South    116
West     115
Name: count, dtype: int64

In [ ]:
df_merged.groupby('product')['sales'].sum()

product
Keyboard    260675.81
Laptop      317281.14
Monitor     281509.14
Mouse       299401.20
Phone       245079.73
Tablet      262582.76
Name: sales, dtype: float64

In [ ]:
bins=[0, 100, 500, 1000, 5000]
labels=['low', 'medium', 'high', 'very high']
df_merged['sales_category'] = pd.cut(df_merged['sales'], bins=bins, labels=labels)

In [ ]:
df_merged

,order_id,date,region,product,category,customer_type,quantity,price,sales,customer_rating,sales_category
0,1,2024-04-12,East,Laptop,Electronics,Returning,8,590,4295.20,1,very high
1,2,2024-12-14,South,Monitor,Accessories,Returning,2,262,429.68,1,medium
2,3,2024-09-27,North,Phone,Accessories,New,5,512,2329.60,2,very high
3,4,2024-04-16,West,Mouse,Electronics,Returning,1,485,441.35,1,medium
4,5,2024-03-12,West,Phone,Electronics,Returning,7,332,1812.72,4,very high
...,...,...,...,...,...,...,...,...,...,...,...
495,496,2024-11-20,South,Mouse,Accessories,Returning,6,314,1450.68,3,very high
496,497,2024-01-04,North,Phone,Accessories,Returning,9,369,2557.17,4,very high
497,498,2024-01-16,South,Keyboard,Electronics,Returning,6,722,3725.52,4,very high
498,499,2024-10-06,North,Phone,Accessories,Returning,2,1449,2550.24,1,very high
499,500,2024-12-01,North,Monitor,Electronics,New,2,869,1581.58,1,very high

In [ ]:
df_merged.set_index('order_id', inplace=True)

In [ ]:
df_merged.to_csv('merged_data.csv', index=False)

In [ ]:
df_merged

,date,region,product,category,customer_type,quantity,price,sales,customer_rating,sales_category
order_id,,,,,,,,,,
1,2024-04-12,East,Laptop,Electronics,Returning,8,590,4295.20,1,very high
2,2024-12-14,South,Monitor,Accessories,Returning,2,262,429.68,1,medium
3,2024-09-27,North,Phone,Accessories,New,5,512,2329.60,2,very high
4,2024-04-16,West,Mouse,Electronics,Returning,1,485,441.35,1,medium
5,2024-03-12,West,Phone,Electronics,Returning,7,332,1812.72,4,very high
...,...,...,...,...,...,...,...,...,...,...
496,2024-11-20,South,Mouse,Accessories,Returning,6,314,1450.68,3,very high
497,2024-01-04,North,Phone,Accessories,Returning,9,369,2557.17,4,very high
498,2024-01-16,South,Keyboard,Electronics,Returning,6,722,3725.52,4,very high
499,2024-10-06,North,Phone,Accessories,Returning,2,1449,2550.24,1,very high
500,2024-12-01,North,Monitor,Electronics,New,2,869,1581.58,1,very high

In [ ]:
import seaborn
print(seaborn.__version__)

0.13.2

In [ ]:
df_merged['sales'].sb(kind='hist', bins=5, title='Sales Distribution')

TypeError: 'Series' object is not callable