In [7]:
import numpy as np
import pandas as pd
df1=pd.DataFrame({"name":['khadija','ali'],"age":[24,19]})
df1

      name  age
0  khadija   24
1      ali   19

In [1]:
# Using a larger dataset
import pandas as pd
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank'],
    'Age': [25, 30, 35, 28, 25, 32],
    'Salary': [50000, 60000, 70000, 55000, 52000, 68000],
    'Department': ['HR', 'IT', 'IT', 'Finance', 'HR', 'IT'],
    'Experience': [2, 5, 8, 3, 2, 6]
})

# head() and tail()
print(df.head(2))
print(df.tail(2))

# unique() and nunique()
print(df['Department'].unique())
print(df['Department'].nunique())

# value_counts()
print(df['Department'].value_counts())
print(df['Age'].value_counts())

    Name  Age  Salary Department  Experience
0  Alice   25   50000         HR           2
1    Bob   30   60000         IT           5
    Name  Age  Salary Department  Experience
4    Eve   25   52000         HR           2
5  Frank   32   68000         IT           6
['HR' 'IT' 'Finance']
3
Department
IT         3
HR         2
Finance    1
Name: count, dtype: int64
Age
25    2
30    1
35    1
28    1
32    1
Name: count, dtype: int64

In [9]:
df['Department'].unique()

<StringArray>
['HR', 'IT', 'Finance']
Length: 3, dtype: str

In [10]:
df.iloc[:,3].replace('IT', np.nan)

0         HR
1        NaN
2        NaN
3    Finance
4         HR
5        NaN
Name: Department, dtype: str

In [11]:
df.isnull().sum()

Name          0
Age           0
Salary        0
Department    0
Experience    0
dtype: int64

In [12]:
df.dropna()

      Name  Age  Salary Department  Experience
0    Alice   25   50000         HR           2
1      Bob   30   60000         IT           5
2  Charlie   35   70000         IT           8
3    David   28   55000    Finance           3
4      Eve   25   52000         HR           2
5    Frank   32   68000         IT           6

##Pandas Tasks

In [15]:
import pandas as pd
data = {'Name':['Alice', 'ali' ,'ahmed','hamad' , 'babar', 'noman' , 'bakar', 'zain','mudassir','danyal'],
         'Age':[34,35,24,16,12,14,15,25,18,19],
         'Roll No': [1,2,3,4,5,6,7,8,9,10],
         'Marks':[88,45,67,87,99,34,54,56,63,44]}
df= pd.DataFrame(data)
print(df)

       Name  Age  Roll No  Marks
0     Alice   34        1     88
1       ali   35        2     45
2     ahmed   24        3     67
3     hamad   16        4     87
4     babar   12        5     99
5     noman   14        6     34
6     bakar   15        7     54
7      zain   25        8     56
8  mudassir   18        9     63
9    danyal   19       10     44

In [16]:
df.dropna()

       Name  Age  Roll No  Marks
0     Alice   34        1     88
1       ali   35        2     45
2     ahmed   24        3     67
3     hamad   16        4     87
4     babar   12        5     99
5     noman   14        6     34
6     bakar   15        7     54
7      zain   25        8     56
8  mudassir   18        9     63
9    danyal   19       10     44

In [17]:
df_replace = df.replace({
    "Ali": "Ali Khan",
    45: 96
})

print("\nAfter Replacing:\n", df_replace)

After Replacing:
        Name  Age  Roll No  Marks
0     Alice   34        1     88
1       ali   35        2     96
2     ahmed   24        3     67
3     hamad   16        4     87
4     babar   12        5     99
5     noman   14        6     34
6     bakar   15        7     54
7      zain   25        8     56
8  mudassir   18        9     63
9    danyal   19       10     44

In [18]:
df.dropna()

       Name  Age  Roll No  Marks
0     Alice   34        1     88
1       ali   35        2     45
2     ahmed   24        3     67
3     hamad   16        4     87
4     babar   12        5     99
5     noman   14        6     34
6     bakar   15        7     54
7      zain   25        8     56
8  mudassir   18        9     63
9    danyal   19       10     44

In [19]:
df_drop_column = df.drop("Marks", axis=1)
print("\nAfter Dropping Column:\n", df_drop_column)

After Dropping Column:
        Name  Age  Roll No
0     Alice   34        1
1       ali   35        2
2     ahmed   24        3
3     hamad   16        4
4     babar   12        5
5     noman   14        6
6     bakar   15        7
7      zain   25        8
8  mudassir   18        9
9    danyal   19       10

In [20]:
df.dropna()

       Name  Age  Roll No  Marks
0     Alice   34        1     88
1       ali   35        2     45
2     ahmed   24        3     67
3     hamad   16        4     87
4     babar   12        5     99
5     noman   14        6     34
6     bakar   15        7     54
7      zain   25        8     56
8  mudassir   18        9     63
9    danyal   19       10     44

In [5]:
import pandas as pd
import numpy as np
df=pd.DataFrame(np.random.randn(50,50))

In [6]:
df

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,-0.022689,1.828224,0.567677,-0.939340,-0.459061,-0.273752,0.613040,-2.260473,1.071630,0.725271,...,-0.490857,0.785561,0.847699,0.593354,2.965561,0.747574,-0.641975,-0.635904,0.467570,-0.566657
1,-0.592025,0.028409,0.556431,0.125137,-0.590912,-1.054549,-0.114750,1.902491,1.601447,1.093038,...,-1.020231,-0.725736,-1.962602,-0.365659,0.430019,0.887981,0.651223,-1.396386,-1.330181,-2.879443
2,-3.056494,-0.303475,0.921045,0.672818,1.289533,-2.451655,0.471081,-0.339969,0.064792,-1.332668,...,0.467842,1.398799,0.599794,0.265057,0.245952,0.238569,0.353102,1.180423,0.504875,0.294915
3,-0.055650,0.379595,1.425451,-0.382774,-1.889900,-0.212912,-0.316646,-0.875493,-1.628603,-1.761362,...,-1.678737,-0.226227,-0.410351,0.877232,-0.043668,-0.747879,0.471280,-0.497789,0.256556,-0.017103
4,0.894236,0.832019,0.998699,0.185943,-0.902059,-0.448620,-0.342720,-2.610453,-1.307007,-0.592477,...,1.015412,0.096838,-0.229099,1.125125,1.475431,0.542149,-0.466770,0.721424,1.109299,0.649212
5,0.647570,0.328028,0.020079,1.414890,1.287171,-0.220089,-1.081718,0.092754,-0.758851,-0.571612,...,-0.059517,-0.956583,0.942320,3.069913,-0.713918,0.335491,-0.376274,-1.333267,-0.198185,0.064690
6,-0.499683,0.454753,-0.656220,1.713880,-0.512405,0.879546,0.718601,-1.965908,-1.378283,-1.147654,...,0.121243,0.593193,1.327277,1.586104,-0.504953,0.382721,-1.226604,-0.459344,-0.366602,0.931820
7,0.424540,-1.114556,1.027642,-1.730194,-0.611721,1.003185,0.038509,-0.720940,1.085868,-0.853994,...,0.496579,-0.225922,-0.660615,1.169207,-0.259590,1.205189,-0.327579,0.333844,1.370371,-0.101803
8,2.902142,0.260143,-1.582264,0.409207,-1.153558,0.243337,0.341249,-0.072272,-0.411209,-0.414505,...,-0.300361,-1.535598,1.003715,2.890193,0.592845,0.496824,0.327508,1.172145,1.568762,0.516829
9,0.737851,0.381305,-0.513762,-0.753474,0.074465,0.508840,-0.319652,0.230645,-0.621483,0.509356,...,0.660414,0.570933,-1.306908,-1.001035,-1.265637,-1.220456,-1.555548,-1.373799,-0.220468,-0.051552
10,-0.319696,0.703838,-0.292224,0.806897,1.136590,-0.437577,-0.507917,-0.383952,-2.240604,-0.085573,...,-2.118811,0.772400,0.150041,-0.159763,0.160051,0.549871,-1.232710,-0.902761,0.141912,-0.520091
11,-0.223852,0.704004,0.772407,-0.002685,0.323092,-0.665803,0.752980,0.160280,0.929788,-0.755294,...,-0.630519,0.809977,1.398372,-0.320224,1.232927,-0.552178,1.937721,-0.506474,0.740093,0.700989
12,-0.098242,0.146386,0.875698,0.279271,0.999397,1.809358,1.488920,-1.259196,-0.195666,-0.189448,...,-1.705952,-0.109127,-1.081008,-1.549928,-1.139414,-0.557814,-0.138482,0.776818,1.816905,0.980094
13,1.122769,-0.194965,0.786509,0.159509,0.742047,0.013633,-1.494119,1.173283,-1.736494,0.493622,...,0.535890,0.593267,-1.061375,-0.568939,-0.586445,1.143756,1.089286,0.560885,0.807461,-1.305579
14,-2.754557,0.109880,1.216593,-0.120651,-0.419216,0.532804,-0.401835,0.264500,0.898345,0.923612,...,1.580270,-0.067476,0.771485,0.020393,0.104050,-2.339149,-0.431949,1.754476,-0.385519,0.521733
15,-1.835570,0.488983,1.539877,-0.473508,2.700864,-0.282087,-0.977479,-1.250906,0.539067,0.258106,...,-2.071280,0.046265,0.447012,1.328069,2.121148,0.411534,-1.179712,-0.125779,0.945368,0.817935
16,0.048246,-0.016415,0.953996,2.395911,-0.480568,1.016219,-1.472857,-1.393353,-0.659574,0.487222,...,0.185177,1.671460,1.085129,-0.310182,0.678615,0.256416,-0.680738,0.882019,0.210261,-0.902421
17,0.772973,0.775572,-1.058050,0.225622,-0.069750,1.271618,1.073789,0.538459,-0.775377,0.196320,...,-0.352846,-2.013302,0.348197,-0.078909,-0.301866,-1.307476,-1.204974,0.391217,0.587708,0.376708
18,0.045517,0.271750,-1.123567,-1.378264,-2.155492,-0.623410,1.770818,1.267566,0.373641,-1.419526,...,0.323765,-0.509642,0.917146,-1.410129,0.379743,-0.926570,0.546607,-0.037158,0.493372,-1.206618
19,0.615524,0.150654,-0.117204,-0.524690,1.002963,-0.525726,-0.414682,-1.565343,-0.025887,-1.575845,...,-1.067078,-1.517526,-2.171393,-1.755229,1.223117,-0.194775,0.041967,0.694545,1.342467,0.324329
20,0.258285,-0.148703,-0.214673,1.236468,0.889272,0.057095,-0.894166,-0.709747,1.005742,1.588115,...,1.465506,-0.645325,0.230771,1.937038,0.605743,0.101735,0.448271,-1.654804,-1.466191,0.108450
21,-0.226020,-1.580869,-1.593385,-0.407655,2.291638,0.134239,0.971588,0.131131,1.454239,-0.296216,...,-0.641355,-1.360569,0.014650,1.056525,1.734311,-0.054176,-1.039654,-0.230943,-0.731622,0.832915
22,0.420332,0.324844,-0.190895,0.541766,0.490263,0.064587,1.072508,-0.757770,1.576902,-0.923172,...,-1.496725,-1.167699,-0.507900,-2.936658,-0.499046,0.319711,0.202047,-0.710711,-0.324853,0.337155
23,-1.194935,-1.125592,-1.120425,0.320002,0.075279,-0.209197,0.283657,0.753232,-1.715430,-0.447502,...,-0.360485,0.260426,0.458299,-0.360019,2.334394,-0.310136,0.268134,1.581235,-0.234227,-1.154998
24,0.629949,-0.460848,0.435720,0.229058,0.585089,0.631164,-0.207222,-0.202282,-0.115474,-1.575508,...,0.897380,-0.558371,-1.319510,0.553339,-2.487012,-0.515541,0.573895,1.242340,-1.269425,-0.323169
25,2.035828,0.239945,-0.034658,0.434527,0.988681,-0.427158,1.094418,0.955438,0.586797,-0.635964,...,-0.358775,0.396771,-0.066886,-0.765366,-0.969032,-1.054135,0.488357,0.122531,0.347815,0.481578
26,-0.333572,-0.789539,-0.098931,-0.353132,-1.534018,-1.817587,0.111643,2.610526,-2.140108,1.565627,...,0.399459,-0.408868,-0.544974,-0.996215,1.561823,-0.980320,0.252058,-0.277970,-1.406599,0.872834
27,-0.984241,1.166252,1.060208,-1.486261,1.064451,1.749122,-0.252856,-2.472002,0.482945,-0.260348,...,1.186069,-0.264669,1.078291,2.342175,-0.735865,0.333142,1.627914,-0.165009,0.963111,-0.310049
28,0.423321,-1.517241,0.785026,-0.634928,0.310075,0.014612,-1.020667,0.201852,0.397766,-0.577589,...,0.416673,0.772891,0.573759,-0.697577,-0.171474,1.040229,-0.911083,-0.497141,0.696018,0.163389
29,-0.768845,-0.551174,1.251822,-0.658475,-0.284889,-0.861255,-0.265497,-2.507003,-0.737790,-1.241164,...,-0.461048,-0.933292,-1.358516,0.823455,-1.340344,-0.245052,1.819938,0.244506,0.919715,-0.030386
30,0.182709,1.725528,-0.762854,-0.060844,-0.837514,-0.258943,-0.624662,-0.550274,1.771587,0.318542,...,-1.732891,-1.451561,0.233086,-1.317689,-0.445892,0.608274,-1.591524,-0.802882,0.589203,-0.439911
31,-0.222359,-0.323501,-1.055735,0.657479,0.419083,0.860302,1.506978,0.945823,1.797024,-0.971910,...,0.483722,0.696536,0.115082,-1.657990,-1.564393,1.602571,-0.330972,-1.274876,0.798821,0.940309
32,-0.054500,1.169532,-1.182851,-0.925656,0.282977,-0.263230,0.221944,-0.279583,-0.241432,0.372687,...,-1.355539,0.174384,1.536109,0.589448,-1.038414,-0.916731,1.045502,0.930074,-1.794958,0.441078
33,-0.787470,0.134014,-2.206850,-0.272895,2.058312,-1.194039,0.412868,1.113047,1.185558,-0.278650,...,0.713706,1.037790,-0.726764,-0.339690,0.630576,-2.225685,0.314098,0.748279,0.075073,0.833533
34,-0.868518,0.745981,-0.921192,-0.092469,0.287112,-0.590877,0.717797,0.169221,-0.611775,1.598118,...,1.389273,0.325515,-0.623425,0.262892,1.744616,0.882589,-0.645371,0.216762,0.175371,-0.121835
35,-0.898348,1.143143,0.258743,-0.974952,-0.006740,-0.907559,1.531715,1.211233,1.081447,-1.795025,...,-0.878951,-1.909431,-0.485724,-0.914414,-0.086423,0.205892,-1.446913,0.526365,0.400311,-0.367636
36,1.491327,-0.420088,0.489765,-0.400932,-0.428318,-0.025214,1.370787,-1.075470,-0.084797,-1.059432,...,-0.102032,-0.512570,-1.349179,0.572706,0.293330,0.355047,0.084428,0.916405,-1.309413,-1.403188
37,-0.429732,-0.866503,-1.262638,-1.120482,-0.914392,0.424933,1.213002,-0.546460,-0.749158,1.540101,...,0.299003,1.368571,1.521454,-0.499642,-1.470995,0.001524,-0.320539,-0.072995,0.584267,0.901703
38,0.000570,0.115983,-0.276933,0.379733,0.707523,1.085975,0.722497,-0.262087,-1.678865,-0.852744,...,-1.028488,-0.701477,0.936543,-1.360474,-2.065304,0.779059,-0.493399,0.874235,0.873524,-1.717399
39,0.760969,-1.325703,0.093326,0.741367,-1.034421,-1.295160,0.484443,0.429622,-0.186430,-0.223013,...,-1.068677,0.105848,-0.463576,0.400174,-0.181509,-0.240717,-1.316697,0.818828,1.133601,1.824936
40,-0.308537,-0.842360,0.809265,-1.224223,-0.515541,-1.303274,-1.355978,-1.508916,2.217810,-0.671853,...,1.599463,-0.944115,0.603876,-0.475950,-0.649027,-1.351872,-0.182417,-0.373346,-1.136664,-0.422564
41,0.067719,-0.000415,-0.084034,0.248517,0.190750,1.052469,0.827464,0.028141,-1.724112,1.268726,...,0.527435,-0.879068,0.881467,-1.005471,-0.516625,-0.551091,-0.408279,-0.612422,-1.228523,0.438891
42,1.243072,1.315443,-0.335038,-0.165451,-0.013348,-0.953432,0.379201,1.000297,0.662116,0.061721,...,-0.331494,0.012866,-0.924925,-1.292931,-0.827782,1.096372,-0.983056,1.124171,0.061194,0.693505
43,-0.618718,-0.457831,1.093143,-1.091845,0.878260,-0.015758,-1.204721,-1.246584,1.067951,0.558368,...,-0.000102,-1.851633,0.214416,-0.138027,-0.673374,1.468348,0.043962,-1.178825,-2.083546,0.398892
44,0.572160,0.979988,-0.540832,0.354182,-0.987183,-1.077865,-1.578377,-0.629389,-1.151645,0.952848,...,-0.906203,1.307790,0.339091,0.214602,-0.652087,0.179695,0.401666,0.409730,1.455803,-0.827652
45,-0.359268,-0.598058,1.774587,2.162904,-1.850018,1.200784,-0.903721,-1.107074,-0.677825,1.135160,...,-1.052406,1.369304,0.306460,-0.360073,0.583110,0.409086,0.183619,-0.872110,-0.149990,0.316688
46,-0.431875,0.007064,0.852620,0.163960,-1.974267,-0.664273,-0.134882,1.779983,-0.431991,0.380595,...,-1.563370,-0.107533,-1.063290,0.468626,0.130409,-1.374228,0.824505,-0.087016,0.130982,-0.731999
47,0.456201,0.137225,-0.267904,0.569079,0.362805,-1.328732,-0.323859,-0.677370,-1.697575,-1.268618,...,1.251209,0.676567,1.528680,0.094418,0.941766,0.565834,-0.517266,-0.843593,0.772998,1.031424
48,0.336456,1.582999,0.493503,-0.239570,-0.395504,-0.311774,-1.388473,-1.201025,0.182793,1.198814,...,0.245550,0.934717,-0.371997,1.016769,-1.101341,-1.698926,-0.887062,-1.020138,-0.545687,1.751711
49,-0.247552,0.065028,0.409539,-0.315131,1.313852,-1.091486,-1.591371,-1.259522,-2.072323,-1.715221,...,0.609852,1.200279,-2.042333,-0.704185,0.274214,-0.180937,0.270548,0.113694,1.693626,0.247035