In [9]:
import pandas as pd
import numpy as np
std_df = pd.read_csv('student_data_clean.csv')
std_df

,Student_ID,Name,Age,Gender,Department,Semester,CGPA,Attendance_Rate,Scholarship,Admission_Date,Midterm_Marks,Final_Marks,City,Study_Hours_Per_Day,Fees_Paid
0,1001,Student_0,24,Other,Math,3,NaN,61.0,False,2021-09-11,26,33,Multan,10,NaN
1,1002,Student_1,21,Female,EE,1,3.94,98.0,False,2020-01-26,0,39,Lahore,5,Installment
2,1003,Student_2,22,Other,EE,5,2.44,66.0,False,2022-08-14,20,46,Faisalabad,7,Full
3,1004,Student_3,24,Male,EE,4,3.47,91.0,False,2021-02-24,19,14,Faisalabad,8,Full
4,1005,Student_4,20,Male,CS,2,3.53,79.0,False,2021-10-24,12,10,Karachi,3,Installment
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1025,1026,Student_25,18,Other,Math,8,2.01,89.0,False,2022-05-23,3,17,Multan,9,Installment
1026,1027,Student_26,21,Other,BBA,6,3.87,57.0,False,2021-02-12,15,13,Karachi,8,Full
1027,1028,Student_27,19,Female,Math,1,3.64,89.0,False,2020-10-26,7,17,Islamabad,8,Installment
1028,1029,Student_28,23,Male,EE,5,3.62,93.0,True,2022-06-26,15,27,Islamabad,5,Pending
1029,1030,Student_29,22,Other,Math,2,3.77,72.0,False,2021-08-24,26,23,Islamabad,9,Full

In [10]:
std_df.drop_duplicates(inplace=True)
std_df

,Student_ID,Name,Age,Gender,Department,Semester,CGPA,Attendance_Rate,Scholarship,Admission_Date,Midterm_Marks,Final_Marks,City,Study_Hours_Per_Day,Fees_Paid
0,1001,Student_0,24,Other,Math,3,NaN,61.0,False,2021-09-11,26,33,Multan,10,NaN
1,1002,Student_1,21,Female,EE,1,3.94,98.0,False,2020-01-26,0,39,Lahore,5,Installment
2,1003,Student_2,22,Other,EE,5,2.44,66.0,False,2022-08-14,20,46,Faisalabad,7,Full
3,1004,Student_3,24,Male,EE,4,3.47,91.0,False,2021-02-24,19,14,Faisalabad,8,Full
4,1005,Student_4,20,Male,CS,2,3.53,79.0,False,2021-10-24,12,10,Karachi,3,Installment
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1996,Student_995,23,Male,Math,3,3.88,81.0,False,2021-01-02,23,10,Islamabad,5,Full
996,1997,Student_996,18,Other,EE,7,3.55,89.0,False,2020-07-30,4,19,Multan,4,Installment
997,1998,Student_997,24,Female,Math,6,2.26,62.0,True,2021-07-30,23,47,Islamabad,8,Pending
998,1999,Student_998,21,Other,BBA,3,2.70,69.0,False,2022-08-18,23,8,Karachi,7,Installment
999,2000,Student_999,23,Female,BBA,3,2.87,84.0,False,2020-07-27,5,1,Lahore,6,Pending

In [17]:
std_df.dropna(inplace=True)
std_df

,Student_ID,Name,Age,Gender,Department,Semester,CGPA,Attendance_Rate,Scholarship,Admission_Date,Midterm_Marks,Final_Marks,City,Study_Hours_Per_Day,Fees_Paid
1,1002,Student_1,21,Female,EE,1,3.94,98.0,False,2020-01-26,0,39,Lahore,5,Installment
2,1003,Student_2,22,Other,EE,5,2.44,66.0,False,2022-08-14,20,46,Faisalabad,7,Full
3,1004,Student_3,24,Male,EE,4,3.47,91.0,False,2021-02-24,19,14,Faisalabad,8,Full
4,1005,Student_4,20,Male,CS,2,3.53,79.0,False,2021-10-24,12,10,Karachi,3,Installment
6,1007,Student_6,22,Female,Math,3,2.06,68.0,False,2022-05-02,8,23,Islamabad,2,Full
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1996,Student_995,23,Male,Math,3,3.88,81.0,False,2021-01-02,23,10,Islamabad,5,Full
996,1997,Student_996,18,Other,EE,7,3.55,89.0,False,2020-07-30,4,19,Multan,4,Installment
997,1998,Student_997,24,Female,Math,6,2.26,62.0,True,2021-07-30,23,47,Islamabad,8,Pending
998,1999,Student_998,21,Other,BBA,3,2.70,69.0,False,2022-08-18,23,8,Karachi,7,Installment
999,2000,Student_999,23,Female,BBA,3,2.87,84.0,False,2020-07-27,5,1,Lahore,6,Pending

In [18]:
pd.pivot_table(std_df, values='CGPA', index='Department', columns='Semester', aggfunc='mean')

Semester,1,2,3,4,5,6,7,8
Department,,,,,,,,
BBA,2.940435,2.816667,3.142258,3.037368,2.980000,2.930000,3.228571,3.131111
CS,3.179615,3.030833,3.077500,3.299615,2.922593,2.939545,3.035556,2.965333
EE,2.994500,2.788750,3.176000,3.013636,3.113182,3.271875,2.962857,2.896522
Math,3.109310,2.931500,3.040345,3.130333,2.926957,3.013077,3.219600,3.002000
Physics,3.048000,3.056667,2.998485,2.989545,2.909545,3.060385,3.050870,3.104000